//>>built
require({cache:{"dojo/_base/query":function(){define(["../query","./NodeList"],function(e){return e})},"rc/reliable/Authentication":function(){define("dijit/_Widget dijit/registry dojo/_base/declare dojo/_base/event dojo/_base/fx dojo/_base/lang dojo/_base/url dojo/cookie dojo/dom-class dojo/dom-construct dojo/dom-style dojo/has dojo/i18n!rc/nls/all dojo/i18n!rc/nls/auth dojo/i18n!rc/nls/errorMessages dojo/io-query dojo/on dojo/query require ../_base/util ../session ../xhr dijit/form/Button dijit/form/Form dijit/form/TextBox dojo/sniff".split(" "),
function(e,m,g,k,n,d,h,r,a,u,l,t,p,q,c,x,v,f,y,w){return g("rc/reliable/Authentication",e,{src:"",pointInstance:1,mainController:1,subController:1,subnet:0,mnemonic:"",instance:null,controller:null,testMode:!1,updating:!1,_fetchPath:y.toUrl("rc/tests/proxy.php"),_url:"",_updating:!1,title:p.loginToMPW,constructor:function(){this.redirectPath=rc.session.getRedirect();window.document.title=w.unescapeHtml(this.title)},postCreate:function(){this.inherited(arguments);if(r.isSupported()){this._loadSysName();
try{this.content=f(".mpwLogin")[0];this._preloader=this._createLoader();this._showLoader();this._messageBox=f(".mpwLoginMessage",this.content)[0];this._loginBox=f(".mpwLoginForm",this.content)[0];this._loginForm=f("form",this._loginBox).map(m.byNode)[0];this._loginMessage=f("label",this._loginForm.domNode)[0];this._sysNameSpan=f("span",this._loginForm.domNode)[0];this._loginUsernameLabel=f(".leadlabel",this._loginForm.domNode)[0];this._loginPasswordLabel=f(".leadlabel",this._loginForm.domNode)[1];
this._loginBtnTxt=f(".dijitButtonText",this._loginForm.domNode)[0];this.waiting=f("#waiting",this._loginForm.domNode)[0];var b=f("input",this._loginForm.domNode);this._userText=b[0];this._passText=b[1]}catch(z){console.error("where is the html form??",z);return}a.remove(this.content,"offscreen");this.own(v(this._loginForm,"submit",d.hitch(this,this.submitForm)));this._hideWaiting();t("trident")&&(7>t("trident")&&this._setMessage("\x3cp class\x3d'alert-message'\x3e"+c.unsupportedBrowser+"\x3c/p\x3e\x3cp class\x3d'alert-message'\x3e"+
c.internetExplorer+"\x3c/p\x3e"),this.own(v(this._userText,"keydown",d.hitch(this,this._keyHandler)),v(this._passText,"keydown",d.hitch(this,this._keyHandler))));this._url=new h(window.location);this._url.query?1==x.queryToObject(this._url.query).logoff&&(rc.session.logout(),this._setMessage(q[211]),this._clearLoader()):rc.session.authenticate().then(d.hitch(this,function(b){this._redirect()}),d.hitch(this,function(b){this._clearLoader()}));this._userText.focus()}else this._setMessage(q.cookies),
l.set(this._loginBox,{display:"none"})},submitForm:function(b){b&&k.stop(b);this.login(this._userText.value,this._passText.value);return!1},_keyHandler:function(b){13==b.keyCode&&this.submitForm(b)},login:function(b,a){this._clearMessage();this._showWaiting();var c=rc.session.login(b,a);c.then(d.hitch(this,function(b){this._redirect()}),d.hitch(this,function(b){var a=b.status,c=q[a];c&&c.length||(c=q.unknown,a&&(c+=" '"+b.message+"' "),c+="\x3c/p\x3e\x3cp\x3e"+q.pleaseReload);this._failLogin(c)}));
return c},cancel:function(b){},_setMessage:function(b){b&&b.length?(this._messageBox.innerHTML="\x3cp\x3e"+b+"\x3c/p\x3e",l.set(this._messageBox,{visibility:"visible"})):this._clearMessage()},_clearMessage:function(){this._messageBox.innerHTML="";l.set(this._messageBox,{visibility:"hidden"})},_redirect:function(){this.destroy();rc.session.setRedirect(null);window.location=this.redirectPath},_failLogin:function(b){this._hideWaiting();this._setMessage(b);this._passText.value="";this._userText.focus()},
_createLoader:function(){return u.create("div",{id:"preloader",className:"preloader"},this.content,"first")},_showLoader:function(){l.set(this._preloader,{opacity:.99,display:"block"})},_clearLoader:function(){n.fadeOut({node:this._preloader,duration:750,onEnd:function(b){l.set(b,"display","none")}}).play()},_showWaiting:function(){l.set(this.waiting,{opacity:.99,display:"block"})},_hideWaiting:function(){this.waiting&&n.fadeOut({node:"waiting",duration:500,onEnd:d.hitch(this,function(b){l.set(b,
"display","none")})}).play()},_loadSysName:function(){rc.xhr.request({type:"cmd",cmdObj:{cmd:9}}).always(d.hitch(this,this._sysNameResponded))},_sysNameResponded:function(b){var a=b.data[0],c="";if(-1===a.indexOf("244"))throw Error("Could not retrieve system name:"+a);c=a.slice(17).replace(/\r\n/,"");if(c=w.escapeHtml(c))this._loginMessage.innerHTML=p.logonMsg;this._sysNameSpan.innerHTML=" \x3cstrong\x3e "+c+"\x3c/strong\x3e";this._loadLoginLabels();return b},_loadLoginLabels:function(){this._loginUsernameLabel.innerHTML=
p.username+": ";this._loginPasswordLabel.innerHTML=p.password+": ";this._loginBtnTxt.innerHTML=p.logonBtn},destroy:function(){u.destroy(this._preloader);this._preloader=null;this.inherited(arguments)}})})},"dijit/form/Form":function(){define("dojo/_base/declare dojo/dom-attr dojo/_base/kernel dojo/sniff ../_Widget ../_TemplatedMixin ./_FormMixin ../layout/_ContentPaneResizeMixin".split(" "),function(e,m,g,k,n,d,h,r){return e("dijit.form.Form",[n,d,h,r],{name:"",action:"",method:"",encType:"","accept-charset":"",
accept:"",target:"",templateString:"\x3cform data-dojo-attach-point\x3d'containerNode' data-dojo-attach-event\x3d'onreset:_onReset,onsubmit:_onSubmit' ${!nameAttrSetting}\x3e\x3c/form\x3e",postMixInProperties:function(){this.nameAttrSetting=this.name?"name\x3d'"+this.name+"'":"";this.inherited(arguments)},execute:function(){},onExecute:function(){},_setEncTypeAttr:function(a){m.set(this.domNode,"encType",a);k("ie")&&(this.domNode.encoding=a);this._set("encType",a)},reset:function(a){var d={returnValue:!0,
preventDefault:function(){this.returnValue=!1},stopPropagation:function(){},currentTarget:a?a.target:this.domNode,target:a?a.target:this.domNode};!1!==this.onReset(d)&&d.returnValue&&this.inherited(arguments,[])},onReset:function(){return!0},_onReset:function(a){this.reset(a);a.stopPropagation();a.preventDefault();return!1},_onSubmit:function(a){var d=this.constructor.prototype;if(this.execute!=d.execute||this.onExecute!=d.onExecute)g.deprecated("dijit.form.Form:execute()/onExecute() are deprecated. Use onSubmit() instead.",
"","2.0"),this.onExecute(),this.execute(this.getValues());!1===this.onSubmit(a)&&(a.stopPropagation(),a.preventDefault())},onSubmit:function(){return this.isValid()},submit:function(){!1!==this.onSubmit()&&this.containerNode.submit()}})})},"*now":function(e){e(['dojo/i18n!*preload*webview/reliable/nls/Authentication*["en-gb","en-us","de","es","es-es","fr","fr-ca","pt","zh","zh-tw","ROOT"]'])}}});
define("webview/reliable/Authentication","dojo/_base/declare dojo/_base/lang dojo/_base/query dojo/dom-attr dojo/i18n!rc/nls/all dojo/i18n!rc/nls/auth dojo/i18n!webview/nls/all dojo/ready dojo/string dojo/topic ../session ../_base/version rc/reliable/Authentication rc/util/notices".split(" "),function(e,m,g,k,n,d,h,r,a,u,l,t,p,q){r(m.hitch(this,function(){g("#version").attr("innerHTML",t.toStringAll())}));return e("webview/reliable/Authentication",p,{title:h.loginToWebview,postCreate:function(){this.inherited(arguments);
this.poweredByText=g(".poweredByText")[0];this.licensedToText=g(".licensedTo")[0]},_redirect:function(){this.destroy();this.redirectPath=rc.session.getRedirect();window.location=this.redirectPath},_setMessage:function(a){q.widget.clear();a&&a.length&&u.publish("sticky",{type:"error",message:a})},_loadLoginLabels:function(){var c="",c=g("#customerName").attr("value")[0],d=g("#numPoints").attr("value")[0],e=g("#expirary").attr("value")[0];k.set(this._loginUsernameLabel,"innerHTML",h.userName+": ");
k.set(this._loginPasswordLabel,"innerHTML",n.password+": ");k.set(this._loginBtnTxt,"innerHTML",n.logonBtn.toLocaleUpperCase());k.set(this.poweredByText,"innerHTML",a.substitute(h.poweredByText,[rc.buildYear,t.toStringAll()]));c=d?1<Number(d)?a.substitute(h.licensedTo,[c,d,e]):a.substitute(h.licensedToSingle,[c,d,e]):h.productNotLicensed;k.set(this.licensedToText,"innerHTML",c)},login:function(a,e){this._clearMessage();this._showWaiting();var c=rc.session.login(a,e);c.then(m.hitch(this,this._redirect),
m.hitch(this,function(a){var c=a.status,e=d[c];e&&e.length||(e="",c&&(e+=" "+a.message+" "));this._messageBox.className="mpwLoginMessage mpwLoginErrorMessage";this._failLogin(e)}));return c}})});
//# sourceMappingURL=Authentication.js.map